### ISSUE TITLE
getPowerState() does not work on Denon X1400

### ISSUE THREAD

**Issue by nneubauer** [k3erg/marantz-denon-telnet#1]
Hi, great project!
I just tried and got it run nicely. It starts and shuts down the receiver but somehow I can't retrieve the status:

```
  this.avr.getPowerState(function(error, data) {
    if(error) {
      that.log("Error while getting power state %s", error);
    }
    callback(null, data);
  });
```

This is my code which results in logging:

```
Error while getting power state Can't connect to device: Error: response not received
```

However the exact same `this.avr` works fine for `setPowerState`.

Further info: I just tried to increase the timeout in the code which does nothing, so the timeout kicks in and results in an error even after 10 seconds.

Any idea?

**Comment by k3erg** [comment]
Hi, txs for the feedback!

I just had a look at the [X1400 protocol](https://usa.denon.com/us/product/hometheater/receivers/avrs930h?docname=AVR-X2400H_X1400H_S930H_S730H_PROTOCOL_V01.xlsx) and I can't see any changes. So that should generally work.

Could you try to use `this.avr.getInput(...)` to see, if we have a general problem on the receiving end?

Mike

**Comment by k3erg** [comment]
... and just for debugging matter: is there a difference with `getPowerState()`, if the device is in standby (powered off) or powered on?

**Comment by nneubauer** [comment]
Awkward. Is there a special mode or flag I can use to get debug information from the underlying telnet client? I'll check tonight and get back to you.

**Comment by nneubauer** [comment]
```
> mdt
MarantzDenonTelnet {
  connectionparams:
   { host: '192.168.0.150',
     port: 23,
     timeout: 1000,
     sendTimeout: 1200,
     negotiationMandatory: false },
  cmdCue: [],
  connection: null }
> mdt.getInput(function(error, data) {console.log('Input is: ' + data);}, 'ZM'); 
undefined
> Input is: undefined
```

As you can see from the above, `getInput` does not work. Neither does `getMuteState`. It seems that no get works but even after failed get requests, the `setPowerState` still works to shut down or power on the AVR. Unfortunately, the connect member is set to null after the request so I can't set the debug flag on it. Any idea on what I can do to debug this?

Also, I am getting the same error on `getPowerState` no matter if device is in standby or on.

Even more debug info, trying to connect raw using telnet-client:

```
> var telnet = require('telnet-client');
undefined
> this.connection = new telnet();
Telnet {
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] },
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  socket: null,
  state: null }
> this.connection.connect('192.168.0.150');
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> Error: connect ECONNREFUSED 127.0.0.1:23
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
> this.connection.connect({host: '192.168.0.150', port: 23});
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> this.connection.send('PW?\r', {timeout: 1000}, function(error, data) { console.log(error); console.log(data); });
Promise {
  _bitField: 1,
  _fulfillmentHandler0:
   { [Function: runBound]
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        members: [] } },
  _rejectionHandler0:
   { [Function: runBound]
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        members: [] } },
  _promise0: [Function],
  _receiver0: [Circular] }
> Error: response not received
    at Timeout.setTimeout [as _onTimeout] (/home/nneubauer/sources/homebridge-denon/node_modules/telnet-client/lib/index.js:215:26)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
undefined
```

... and even more. It seems that going through telnet on command line does not work either.

```
telnet 192.168.0.150
Trying 192.168.0.150...
Connected to 192.168.0.150.
Escape character is '^]'.
PWSTANDBY
PWON
```

Both work, but when I type PW? or MV? nothing is returned. :(

**Comment by k3erg** [comment]
OK, so it is not related to this lib. I will add some debugging options none the less.

Going down the pearl-chain... the telnet connection to these devices is stateless (negotiationMandatory: false). I.e. there is no handshake and you might be able to send commands even dough there is no backwards connection.

Just to rule out filtering of hubs/routers/switches and firewalls... have you tried to connect via eth-cable / wifi directly and checked on rules for incoming connections on your machine?

I have a Denon 1200 in my shed. Maybe I get it in to run some tests on that unit.

**Comment by nneubauer** [comment]
Oh man! After inspecting the AVR options and checking the network diagnostics, it hung forever. So I decided to unplug the AVR for a minute and reconnect to power. And... tada! Everything works as expected. Sorry to have bothered you. Great library!

For anyone who get something similar and finds this via google. You can also go to

http://YOURAVRIP:8080/goform/formMainZone_MainZoneXmlStatusLite.xml

If this does not return a value for power, so an empty `<value/>` node, power cycle your AVR.

**Comment by k3erg** [comment]
Txs for following up. I'll add the Denon X1400 to the tested devices, then ;) .

**Comment by nneubauer** [comment]
One caveat you might want to mention is that only one connection at a time is supported by the AVR. I wanted to create a homebridge plugin based on this and if you add two accessories based on this client, one accessory will fail when currently requesting status. ;)

**Comment by k3erg** [comment]
Will do :) – so it was homebridge, too, that brought you here... this is why I had to add a cue for my accessories and I retain the connections in my homebridge-marantz-denon-telnet plugin.

**Comment by nneubauer** [comment]
First of all, great that you separated those projects! I would also love to use your homebridge plugin but that zeroconf, while generally great, is too much magic for me. I was planning to use a switch accessory that is on only if a specific input is set `and` the AVR is on. -- And then have multiple of those. So that I can set a scene that switches the AVR on, to a specific input, switch the TV on, switch the input source on (eg. HTPC). Anyhow, I learned some node while digging into this. ;)
