### ISSUE TITLE
Using a denon 4310 only the first command works.

### ISSUE THREAD

**Issue by ascl00** [k3erg/marantz-denon-telnet#2]
It looks like the default for the telnet client library is to use input/output record separators of irs=\r and ors=\r\n (or maybe the other way around, sorry, doing this by memory), however, my receiver does not use \n at all, it strictly wants a \r only as separator.  This is an easy fix by changing connectionparams to include ors and irs set to '\r', however I don't have a more modern AVR to test this with... but I guess you do?

I would imagine someone thought that limiting it to \r as a delimiter was dumb and updated the software at some point. If it turns out that \r only works on newer AVRs, perhaps it would help someone else out there?

Thanks for creating this library, I am using it for a roon extension to control my AVR's volume (there is one that already exists, but it doesn't work for my AVR, I guess it is too old).

**Comment by k3erg** [comment]
Yes, they are picky about separators. I'm going to test `\r` this evening.

**Comment by ascl00** [comment]
I have no doubt you were able to make the change... but now I'm in front of my computer, I can post a diff:
```
@@ -28,11 +28,13 @@ var MarantzDenonTelnet = function(ip) {
     this.connectionparams = {
         host: ip,
         port: 23,
         timeout: 1000, //  The RESPONSE should be sent within 200ms of receiving the request COMMAND. (plus network delay)
         sendTimeout: 1200,
-        negotiationMandatory: false
+        negotiationMandatory: false,
+        ors: '\r', // Set outbound record separator
+        irs: '\r'
     };
     this.cmdCue = [];
     this.connection = null;
 };
 ```

**Comment by k3erg** [comment]
Finally came around to test this on my receivers and it runs without hiccups. Txs!
