### ISSUE TITLE
Request commands always timeout rather than return when there is a response

### ISSUE THREAD

**Issue by ascl00** [k3erg/marantz-denon-telnet#6]
The way send() gets called means that it always waits for 'timeout' ms, however, at least in a "request" type command, we do know what we should wait for! 

So if we modify the send something like this:
```
            var send_options =  {timeout: (isRequestCommand ? this.connectionparams.timeout : 10)};
            if (isRequestCommand)
            {
                send_options.waitfor = this.connectionparams.irs;
            }
            this.connection.send(item.cmd, send_options, function(error, data) {
```
The callback will fire as soon as telnet sees a record sep (ie \r). This makes 4 queries in a row take < 200ms rather than timeout * 4.

**Comment by k3erg** [comment]
Wrong issue... this on I'll test tonight :)

**Comment by ascl00** [comment]
Did you get a chance to test this out?

**Comment by ascl00** [comment]
I created a pull request, although its mainly for my own benefit (ie better than having local only changes).

**Comment by k3erg** [comment]
Finally got around to give this some more thoughts.

I agree that waiting for the timeout can be improved by just waiting for the required response.

Looping over my collected debug data, unfortunately, the first line, that is returned is not always the required response (if an event is emitted by the avr, it might sneak in between) and a response can be split over multiple lines (like the zone info).

So best would be if a request could submit a distinct ```waitfor``` in the form of maybe a regexp, which could be used to parse the result at the same time.

Looking into telnet possibilities. Keeping this open.

**Comment by ascl00** [comment]
I was thinking about this too actually and the code I suggested can definitely be improved on. Firstly it should eat and \n’s in case some newer AVRs send both. Secondly it can definitely wait for the right response and not just the first... possibly even leaving the “wrong” response on the stack. 

I’ll have another shot at it when I’m back home (a couple of weeks). 

Cheers

**Comment by k3erg** [comment]
Just had a look at node-telnet-client, maybe I can sneak in the regexp for ```waitfor```.

**Comment by k3erg** [comment]
PR for `waitfor` with regexp support for node-telnet-client is out: 
https://github.com/mkozjak/node-telnet-client/pull/119

Meanwhile, I updated the code so that out of all returned data, the correct line is parsed. This enables your push to remove obsolete timeouts.

I'll merge your PR and my uncommitted code, as soon as node-telnet-client merged the PR.

**Comment by k3erg** [comment]
PR and `waitfor` code with regexp support in ;) .
